import React, { useState, useEffect, useMemo } from 'react';
import {
  TelemetryData,
  EngineHealthScores,
  FaultType,
  RulEstimate,
  AiDiagnosticResult,
} from '../../types/engine';
import { VibesparEngineVisualization } from '../VibesparEngineVisualization';
import { AutonomousMaintenanceAdvisory } from '../maintenance/AutonomousMaintenanceAdvisory';
import {
  Wrench,
  Clock,
  CheckCircle2,
  AlertTriangle,
  AlertOctagon,
  Calendar,
  Layers,
  Maximize2,
  Minimize2,
  ClipboardList,
  FileCheck,
  TrendingDown,
  Package,
  FileText,
  Printer,
  Download,
  Share2,
  X,
  CheckSquare,
  ArrowRight,
  Sparkles,
  Info,
  Sliders,
  RotateCcw,
  Bot,
} from 'lucide-react';
import {
  ResponsiveContainer,
  LineChart,
  Line,
  XAxis,
  YAxis,
  Tooltip,
  CartesianGrid,
  AreaChart,
  Area,
} from 'recharts';

interface MaintenanceViewProps {
  telemetry: TelemetryData;
  health: EngineHealthScores;
  activeFault: FaultType;
  rul: RulEstimate;
  diagnostic: AiDiagnosticResult;
  show3DEngine: boolean;
  onToggle3DEngine: () => void;
  theme: 'light' | 'dark';
  onOpenReportsModule?: () => void;
}

export type KanbanColumn = 'RECOMMENDED' | 'SCHEDULED' | 'COMPLETED';

export interface MaintenanceCard {
  id: string;
  component: string;
  advisoryType: 'Clean' | 'Replace' | 'Inspect' | 'Adjust';
  priority: 'Critical' | 'High' | 'Medium' | 'Low';
  estimatedDowntime: string;
  requiredTools: string;
  requiredParts: string;
  status: KanbanColumn;
  description: string;
  autoGenerated?: boolean;
}

export interface ComponentHealthDetail {
  id: string;
  name: string;
  category: string;
  healthHistory: number[]; // 5 intervals across 50 hours
  currentHealth: number;
  failureProbability: number; // %
  wearRate: number; // % per hour
  lastServiceDate: string;
  nextPredictedServiceHours: number;
  recommendedPartNumber: string;
}

export const MaintenanceView: React.FC<MaintenanceViewProps> = ({
  telemetry,
  health,
  activeFault,
  rul,
  diagnostic,
  show3DEngine,
  onToggle3DEngine,
  theme,
  onOpenReportsModule,
}) => {
  const isLight = theme === 'light';

  // Navigation between Autonomous Maintenance Advisory System & Depot Kanban Logbook
  const [activeSubTab, setActiveSubTab] = useState<'AUTONOMOUS_ADVISORY' | 'KANBAN_LOGBOOK'>('AUTONOMOUS_ADVISORY');

  // -------------------------------------------------------------------------
  // PANEL 1: KANBAN ADVISORY BOARD STATE (PERSISTED IN LOCALSTORAGE / CLIENT)
  // -------------------------------------------------------------------------
  const [cards, setCards] = useState<MaintenanceCard[]>(() => {
    const saved = localStorage.getItem('vibespar_kanban_cards');
    if (saved) {
      try {
        return JSON.parse(saved);
      } catch (e) {
        // fallback
      }
    }
    return [
      {
        id: 'card-1',
        component: 'Cylinder 2 Injector',
        advisoryType: 'Clean',
        priority: 'High',
        estimatedDowntime: '1.5 hrs',
        requiredTools: 'Ultrasonic bath, torque wrench (18 Nm)',
        requiredParts: 'Seal kit O-Ring ROT-914-721',
        status: 'RECOMMENDED',
        description: 'CHT delta elevated (+18.4°C). Micro-nozzle cavitation deposits suspected.',
      },
      {
        id: 'card-2',
        component: 'Lubrication Oil Filter Cartridge',
        advisoryType: 'Replace',
        priority: 'High',
        estimatedDowntime: '0.8 hrs',
        requiredTools: 'Filter strap wrench, catch basin',
        requiredParts: 'Oil element ROTAX-914-825-B',
        status: 'SCHEDULED',
        description: 'Differential pressure sensor logged elevated delta P at 12:47 UTC.',
      },
      {
        id: 'card-3',
        component: 'Turbocharger Wastegate Actuator',
        advisoryType: 'Adjust',
        priority: 'Medium',
        estimatedDowntime: '1.2 hrs',
        requiredTools: 'Digital protractor, TCU test harness',
        requiredParts: 'Hi-temp linkage grease AERO-G395',
        status: 'SCHEDULED',
        description: 'Verify 0-100% potentiometer travel alignment and null point calibration.',
      },
      {
        id: 'card-4',
        component: 'Dual Spark Plugs (x8)',
        advisoryType: 'Inspect',
        priority: 'Low',
        estimatedDowntime: '0.5 hrs',
        requiredTools: 'Feeler gauge (0.70mm), 16mm socket',
        requiredParts: 'None (Clean only)',
        status: 'COMPLETED',
        description: 'Routine 50-hour gap audit. Electrodes cleaned and gapped to 0.70mm.',
      },
    ];
  });

  // Save to client-side localStorage on change
  useEffect(() => {
    localStorage.setItem('vibespar_kanban_cards', JSON.stringify(cards));
  }, [cards]);

  // Auto-populate cards based on active AI fault detection
  useEffect(() => {
    if (activeFault === 'OVERHEATING') {
      setCards((prev) => {
        if (prev.some((c) => c.id === 'auto-overheat')) return prev;
        return [
          {
            id: 'auto-overheat',
            component: 'Radiator Heat Exchanger & Water Pump',
            advisoryType: 'Inspect',
            priority: 'Critical',
            estimatedDowntime: '2.0 hrs',
            requiredTools: 'Coolant refractometer, pressure tester',
            requiredParts: 'Evans Waterless Coolant (2.5L)',
            status: 'RECOMMENDED',
            description: 'AI signature match: Cooling system degradation. Airflow blockage or pump cavitation detected.',
            autoGenerated: true,
          },
          ...prev,
        ];
      });
    } else if (activeFault === 'LUBRICATION_FAILURE') {
      setCards((prev) => {
        if (prev.some((c) => c.id === 'auto-oil-loss')) return prev;
        return [
          {
            id: 'auto-oil-loss',
            component: 'Oil Pressure Relief Valve & Scavenge Pump',
            advisoryType: 'Replace',
            priority: 'Critical',
            estimatedDowntime: '3.5 hrs',
            requiredTools: 'Borescope, hydraulic test rig',
            requiredParts: 'Relief valve spring ROT-914-112',
            status: 'RECOMMENDED',
            description: 'AI signature match: Oil pressure decay rate exceeding -0.08 bar/min.',
            autoGenerated: true,
          },
          ...prev,
        ];
      });
    } else if (activeFault === 'MISFIRE') {
      setCards((prev) => {
        if (prev.some((c) => c.id === 'auto-misfire')) return prev;
        return [
          {
            id: 'auto-misfire',
            component: 'Ignition Coil & Spark Lead Cyl #2',
            advisoryType: 'Replace',
            priority: 'Critical',
            estimatedDowntime: '1.0 hrs',
            requiredTools: 'Multimeter, spark gap tester',
            requiredParts: 'Coil pack ROT-914-880-C',
            status: 'RECOMMENDED',
            description: 'Secondary ignition voltage breakdown causing intermittent combustion misfire.',
            autoGenerated: true,
          },
          ...prev,
        ];
      });
    }
  }, [activeFault]);

  const moveCard = (id: string, targetStatus: KanbanColumn) => {
    setCards((prev) =>
      prev.map((c) => (c.id === id ? { ...c, status: targetStatus } : c))
    );
  };

  // -------------------------------------------------------------------------
  // PANEL 2: COMPONENT HEALTH TIMELINE & DETAIL MODAL STATE
  // -------------------------------------------------------------------------
  const [selectedComponentDetail, setSelectedComponentDetail] = useState<ComponentHealthDetail | null>(null);

  const componentsTimelineData: ComponentHealthDetail[] = useMemo(() => [
    {
      id: 'comp-piston-rings',
      name: 'Piston Rings & Cylinder Bore',
      category: 'Mechanical / Combustion',
      healthHistory: [98, 95, 92, 88, health.mechanical || 82],
      currentHealth: health.mechanical || 82,
      failureProbability: 14.2,
      wearRate: 0.32,
      lastServiceDate: '2026-08-14 (Sortie 019)',
      nextPredictedServiceHours: 184,
      recommendedPartNumber: 'ROT-914-RING-SET-STD',
    },
    {
      id: 'comp-bearings',
      name: 'Crankshaft & Rod Bearings',
      category: 'Mechanical / Journal',
      healthHistory: [99, 97, 95, 92, 89],
      currentHealth: 89,
      failureProbability: 8.5,
      wearRate: 0.18,
      lastServiceDate: '2026-07-28 (Sortie 014)',
      nextPredictedServiceHours: 245,
      recommendedPartNumber: 'ROT-914-BRG-TRI-METAL',
    },
    {
      id: 'comp-valves',
      name: 'Exhaust & Intake Valves',
      category: 'Valvetrain / Head',
      healthHistory: [97, 94, 91, 87, 84],
      currentHealth: 84,
      failureProbability: 18.0,
      wearRate: 0.28,
      lastServiceDate: '2026-08-10 (Sortie 018)',
      nextPredictedServiceHours: 142,
      recommendedPartNumber: 'ROT-914-VALVE-EXH-NIMONIC',
    },
    {
      id: 'comp-injectors',
      name: 'Fuel Injector Nozzles (Cyl 1-4)',
      category: 'Fuel Delivery',
      healthHistory: [98, 92, 85, 78, activeFault === 'NORMAL' ? 86 : 64],
      currentHealth: activeFault === 'NORMAL' ? 86 : 64,
      failureProbability: activeFault === 'NORMAL' ? 12.0 : 48.5,
      wearRate: 0.45,
      lastServiceDate: '2026-08-22 (Sortie 021)',
      nextPredictedServiceHours: activeFault === 'NORMAL' ? 112 : 28,
      recommendedPartNumber: 'BOSCH-EV14-ROT-SPEC',
    },
    {
      id: 'comp-oil-pump',
      name: 'Oil Pressure & Scavenge Pump',
      category: 'Lubrication Circuit',
      healthHistory: [99, 95, 89, 79, activeFault === 'LUBRICATION_FAILURE' ? 52 : (health.lubrication || 72)],
      currentHealth: activeFault === 'LUBRICATION_FAILURE' ? 52 : (health.lubrication || 72),
      failureProbability: activeFault === 'LUBRICATION_FAILURE' ? 62.0 : 15.4,
      wearRate: 0.38,
      lastServiceDate: '2026-07-15 (Sortie 011)',
      nextPredictedServiceHours: activeFault === 'LUBRICATION_FAILURE' ? 18 : 68,
      recommendedPartNumber: 'ROT-914-OILPUMP-DUAL',
    },
    {
      id: 'comp-cooling-pump',
      name: 'Coolant Pump & Impeller',
      category: 'Thermal Management',
      healthHistory: [98, 96, 92, 88, activeFault === 'OVERHEATING' ? 58 : 85],
      currentHealth: activeFault === 'OVERHEATING' ? 58 : 85,
      failureProbability: activeFault === 'OVERHEATING' ? 54.0 : 9.8,
      wearRate: 0.22,
      lastServiceDate: '2026-08-01 (Sortie 015)',
      nextPredictedServiceHours: activeFault === 'OVERHEATING' ? 24 : 195,
      recommendedPartNumber: 'ROT-914-PUMP-WATER-CER',
    },
  ], [health, activeFault]);

  // Failure probability Weibull curve data for detail modal
  const failureCurveData = useMemo(() => {
    if (!selectedComponentDetail) return [];
    const points = [];
    const baseP = selectedComponentDetail.failureProbability / 100;
    for (let h = 0; h <= 100; h += 10) {
      // Weibull cumulative hazard shape
      const prob = Math.min(100, Math.round((1 - Math.exp(-Math.pow(h / 65, 2.2))) * 100 * (baseP * 1.5)));
      points.push({ flightHours: `+${h}h`, probability: prob });
    }
    return points;
  }, [selectedComponentDetail]);

  // -------------------------------------------------------------------------
  // PANEL 3: RUL & TBO TRACKER DATA
  // -------------------------------------------------------------------------
  const tboTotalHours = 1200;
  const tboElapsedHours = 1032;
  const tboRemainingHours = tboTotalHours - tboElapsedHours; // 168 hours remaining
  const tboPercent = Math.round((tboRemainingHours / tboTotalHours) * 100);

  const componentRulList = [
    { name: 'Piston Rings', rul: 184, max: 250, status: 'nominal' },
    { name: 'Bearings', rul: 245, max: 300, status: 'nominal' },
    { name: 'Valves', rul: 142, max: 200, status: 'nominal' },
    { name: 'Injector (C2)', rul: activeFault === 'NORMAL' ? 112 : 28, max: 150, status: activeFault === 'NORMAL' ? 'nominal' : 'critical' },
    { name: 'Oil Pump', rul: activeFault === 'LUBRICATION_FAILURE' ? 18 : 68, max: 120, status: activeFault === 'LUBRICATION_FAILURE' ? 'critical' : 'warning' },
    { name: 'Cooling Pump', rul: activeFault === 'OVERHEATING' ? 24 : 195, max: 250, status: activeFault === 'OVERHEATING' ? 'critical' : 'nominal' },
  ];

  // -------------------------------------------------------------------------
  // PANEL 4: PARTS INVENTORY & PROCUREMENT
  // -------------------------------------------------------------------------
  const inventoryItems = [
    {
      partName: 'Cylinder 2 Injector Nozzle (Bosch EV14)',
      stock: 1,
      leadTimeDays: 4,
      reorderQty: 2,
      rulHours: activeFault === 'NORMAL' ? 112 : 28,
      status: activeFault === 'NORMAL' ? 'Adequate' : 'REORDER REQUIRED',
      urgent: activeFault !== 'NORMAL',
    },
    {
      partName: 'Oil Filter Cartridge Element (ROT-914-825)',
      stock: 2,
      leadTimeDays: 2,
      reorderQty: 4,
      rulHours: 45,
      status: 'Adequate',
      urgent: false,
    },
    {
      partName: 'Oil Pressure Relief Valve Assembly',
      stock: 0,
      leadTimeDays: 7,
      reorderQty: 1,
      rulHours: activeFault === 'LUBRICATION_FAILURE' ? 18 : 68,
      status: activeFault === 'LUBRICATION_FAILURE' ? 'STOCKOUT - EXPEDITE' : 'Low Stock',
      urgent: activeFault === 'LUBRICATION_FAILURE',
    },
    {
      partName: 'Spark Plug Set NGK-DCPR8E (Pack of 8)',
      stock: 4,
      leadTimeDays: 1,
      reorderQty: 2,
      rulHours: 210,
      status: 'Optimal',
      urgent: false,
    },
    {
      partName: 'Water Pump Ceramic Seal & Gasket Kit',
      stock: 1,
      leadTimeDays: 5,
      reorderQty: 2,
      rulHours: activeFault === 'OVERHEATING' ? 24 : 195,
      status: activeFault === 'OVERHEATING' ? 'ORDER SUGGESTED' : 'Adequate',
      urgent: activeFault === 'OVERHEATING',
    },
  ];

  // -------------------------------------------------------------------------
  // PANEL 5: MAINTENANCE REPORT GENERATOR MODAL STATE
  // -------------------------------------------------------------------------
  const [isReportModalOpen, setIsReportModalOpen] = useState(false);
  const [isReportExported, setIsReportExported] = useState(false);

  const handlePrint = () => {
    window.print();
  };

  const handleExportCsv = () => {
    const csvContent =
      'data:text/csv;charset=utf-8,' +
      'Parameter,Value\n' +
      'Mission ID,MISSION-027\n' +
      'Date,2026-09-26\n' +
      'UAV Tail,UAV-07\n' +
      'Engine Serial,AERO-PISTON-01 (Rotax 914-F)\n' +
      'Duration,01:42:15\n' +
      `Overall Engine Health,${Math.round(health.overall)}%\n` +
      `Active Fault,${activeFault}\n` +
      `TBO Remaining,${tboRemainingHours} hours\n` +
      `Next Scheduled Service,${rul.minHours} hours\n`;
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', 'VIBESPAR_Mission_027_Maintenance_Report.csv');
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className={`w-full flex flex-col space-y-3.5 font-sans select-none animate-fadeIn max-w-[1920px] mx-auto ${
      isLight ? 'text-slate-800' : 'text-slate-100'
    }`}>
      {/* ========================================================================= */}
      {/* TOP SUMMARY STRIP: DIGITAL MAINTENANCE LOGBOOK & REPORT LAUNCHER          */}
      {/* ========================================================================= */}
      <section className={`border rounded-lg p-3 flex flex-wrap items-center justify-between gap-3 ${
        isLight ? 'bg-white border-slate-200 text-slate-800 shadow-xs' : 'bg-[#0a0e17] border-[#16273f] text-slate-100 shadow-lg'
      }`}>
        <div className="flex items-center space-x-3">
          <div className={`p-2 rounded-md border ${
            isLight ? 'bg-amber-50 border-amber-300 text-amber-700' : 'bg-amber-950/60 border-amber-500/50 text-amber-400'
          }`}>
            <Wrench className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center space-x-2">
              <span className={`font-chakra font-bold text-sm tracking-wider uppercase ${
                isLight ? 'text-slate-900' : 'text-slate-100'
              }`}>
                VIBESPAR DIGITAL MAINTENANCE LOGBOOK & ADVISORY SYSTEM
              </span>
              <span className={`px-2 py-0.5 rounded text-[10px] font-tech font-bold uppercase border ${
                isLight ? 'bg-cyan-50 border-cyan-300 text-cyan-800' : 'bg-cyan-950 border border-cyan-500/60 text-cyan-300'
              }`}>
                DRDO IETM LEVEL 4 AUDITABLE
              </span>
            </div>
            <p className={`text-xs font-mono mt-0.5 ${isLight ? 'text-slate-500' : 'text-slate-400'}`}>
              Automated Kanban Task Board • 50h Component Wear Timeline • RUL & TBO Optimizer
            </p>
          </div>
        </div>

        {/* Action Buttons: Generate Mission Health Report & All Missions Archive */}
        <div className="flex items-center space-x-2.5">
          <button
            onClick={() => setIsReportModalOpen(true)}
            className={`px-3.5 py-1.5 rounded-md border font-chakra font-bold text-xs tracking-wider flex items-center space-x-2 transition-all ${
              isLight
                ? 'bg-cyan-50 hover:bg-cyan-100 border-cyan-300 text-cyan-800 shadow-xs'
                : 'bg-cyan-950/80 hover:bg-cyan-900 border-cyan-500/80 text-cyan-300 shadow-[0_0_15px_rgba(6,182,212,0.3)]'
            }`}
            title="Open Mission-027 single sortie maintenance health report"
          >
            <FileText className={`w-4 h-4 ${isLight ? 'text-cyan-700' : 'text-cyan-400'}`} />
            <span>GENERATE MISSION HEALTH REPORT</span>
          </button>
          {onOpenReportsModule && (
            <button
              onClick={onOpenReportsModule}
              className={`px-3.5 py-1.5 rounded-md border font-chakra font-bold text-xs tracking-wider flex items-center space-x-2 transition-all ${
                isLight
                  ? 'bg-slate-100 hover:bg-slate-200 border-slate-300 text-slate-700 shadow-xs'
                  : 'bg-[#0e1c31] hover:bg-[#162f54] border-[#214376] text-slate-200 shadow-[0_0_10px_rgba(0,0,0,0.5)]'
              }`}
              title="Open the comprehensive multi-mission health reports database"
            >
              <FileCheck className={`w-4 h-4 ${isLight ? 'text-emerald-700' : 'text-emerald-400'}`} />
              <span>ALL MISSIONS ARCHIVE</span>
            </button>
          )}
        </div>
      </section>

      {/* ========================================================================= */}
      {/* SUB-NAVIGATION: AUTONOMOUS AI ADVISORY SYSTEM vs DEPOT KANBAN LOGBOOK     */}
      {/* ========================================================================= */}
      <div className={`flex flex-wrap items-center justify-between gap-2 border p-1.5 rounded-lg ${
        isLight ? 'bg-white border-slate-200 shadow-xs' : 'bg-[#080d19] border-[#16253e] shadow-md'
      }`}>
        <div className="flex flex-wrap items-center gap-1.5">
          <button
            onClick={() => setActiveSubTab('AUTONOMOUS_ADVISORY')}
            className={`px-3 py-1.5 rounded text-xs font-chakra font-bold tracking-wider uppercase transition-all flex items-center space-x-2 border ${
              activeSubTab === 'AUTONOMOUS_ADVISORY'
                ? isLight
                  ? 'bg-cyan-50 text-cyan-800 border-cyan-400 shadow-xs'
                  : 'bg-cyan-950 text-cyan-300 border-cyan-400 shadow-[0_0_14px_rgba(6,182,212,0.35)] ring-1 ring-cyan-400/60'
                : isLight
                ? 'bg-slate-50 text-slate-600 hover:text-slate-900 border-slate-200 hover:bg-slate-100'
                : 'bg-[#050a14] text-slate-400 hover:text-slate-200 border-[#15233a] hover:bg-[#0c1626]'
            }`}
          >
            <Bot className={`w-4 h-4 ${isLight ? 'text-cyan-700' : 'text-cyan-400'}`} />
            <span>⚡ AUTONOMOUS AI ADVISORY SYSTEM</span>
            <span className={`px-1.5 py-0.2 rounded text-[9px] font-mono border ${
              isLight ? 'bg-cyan-100 text-cyan-800 border-cyan-300' : 'bg-cyan-900/80 text-cyan-200 border-cyan-600'
            }`}>
              PROACTIVE
            </span>
          </button>

          <button
            onClick={() => setActiveSubTab('KANBAN_LOGBOOK')}
            className={`px-3 py-1.5 rounded text-xs font-chakra font-bold tracking-wider uppercase transition-all flex items-center space-x-2 border ${
              activeSubTab === 'KANBAN_LOGBOOK'
                ? isLight
                  ? 'bg-amber-50 text-amber-800 border-amber-400 shadow-xs'
                  : 'bg-amber-950 text-amber-300 border-amber-500 shadow-[0_0_14px_rgba(245,158,11,0.3)] ring-1 ring-amber-500/60'
                : isLight
                ? 'bg-slate-50 text-slate-600 hover:text-slate-900 border-slate-200 hover:bg-slate-100'
                : 'bg-[#050a14] text-slate-400 hover:text-slate-200 border-[#15233a] hover:bg-[#0c1626]'
            }`}
          >
            <ClipboardList className={`w-4 h-4 ${isLight ? 'text-amber-700' : 'text-amber-400'}`} />
            <span>📋 DEPOT KANBAN & TBO LOGBOOK</span>
            <span className={`px-1.5 py-0.2 rounded text-[9px] font-mono border ${
              isLight ? 'bg-amber-100 text-amber-800 border-amber-300' : 'bg-amber-950/80 text-amber-300 border-amber-700'
            }`}>
              {cards.length} TASKS
            </span>
          </button>
        </div>

        <div className={`hidden md:flex items-center space-x-3 text-[11px] font-mono pr-2 ${
          isLight ? 'text-slate-500' : 'text-slate-400'
        }`}>
          <span>Weibull-LSTM Hazard Active</span>
          <span>•</span>
          <span className={isLight ? 'text-cyan-700 font-bold' : 'text-cyan-400'}>Rotax 914-F Turbo Twin</span>
        </div>
      </div>

      {/* Conditionally Rendered Sub-View */}
      {activeSubTab === 'AUTONOMOUS_ADVISORY' ? (
        <AutonomousMaintenanceAdvisory
          telemetry={telemetry}
          health={health}
          activeFault={activeFault}
          rul={rul}
          diagnostic={diagnostic}
          theme={theme}
        />
      ) : (
        <>
      {/* ========================================================================= */}
      {/* PANEL 1 — MAINTENANCE ADVISORY BOARD (KANBAN-STYLE 3 COLUMNS)             */}
      {/* ========================================================================= */}
      <section className="bg-[#0a0e17] border border-[#16273f] rounded-lg p-3.5 shadow-md">
        <div className="flex items-center justify-between pb-2 mb-3 border-b border-[#142338]">
          <div className="flex items-center space-x-2">
            <ClipboardList className="w-4 h-4 text-amber-400" />
            <h3 className="text-xs font-chakra font-bold tracking-wider text-slate-200 uppercase">
              PANEL 1: MAINTENANCE ADVISORY BOARD [AI-POPULATED KANBAN]
            </h3>
          </div>
          <div className="flex items-center space-x-3 text-[10px] font-mono text-slate-400">
            <span>Client State Persisted (dcc.Store)</span>
            <span className="text-cyan-400">Total Tasks: {cards.length}</span>
          </div>
        </div>

        {/* 3-Column Kanban Board */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          {/* COLUMN 1: RECOMMENDED ACTIONS */}
          <div className="bg-[#070b13] p-2.5 rounded-lg border border-[#142338] flex flex-col min-h-[300px]">
            <div className="flex items-center justify-between pb-2 mb-2 border-b border-[#142338]">
              <span className="font-chakra font-bold text-xs text-amber-400 uppercase flex items-center space-x-1.5">
                <span className="w-2 h-2 rounded-full bg-amber-400" />
                <span>Recommended Actions</span>
              </span>
              <span className="px-1.5 py-0.5 rounded text-[10px] font-mono bg-amber-950/60 text-amber-300 border border-amber-800">
                {cards.filter((c) => c.status === 'RECOMMENDED').length}
              </span>
            </div>

            <div className="space-y-2 flex-1 overflow-y-auto">
              {cards
                .filter((c) => c.status === 'RECOMMENDED')
                .map((card) => (
                  <div
                    key={card.id}
                    className={`p-2.5 rounded border transition-all ${
                      card.priority === 'Critical'
                        ? 'bg-rose-950/25 border-rose-500/70 shadow-[0_0_8px_rgba(239,68,68,0.2)]'
                        : card.priority === 'High'
                        ? 'bg-amber-950/25 border-amber-500/70'
                        : 'bg-[#0a121e] border-[#182942]'
                    }`}
                  >
                    <div className="flex items-center justify-between text-[11px] font-chakra mb-1">
                      <span className="font-bold text-slate-100">{card.component}</span>
                      <span
                        className={`text-[9px] font-mono px-1 rounded uppercase font-bold ${
                          card.priority === 'Critical'
                            ? 'bg-rose-600 text-white'
                            : card.priority === 'High'
                            ? 'bg-amber-500 text-slate-950'
                            : 'bg-cyan-950 text-cyan-300 border border-cyan-800'
                        }`}
                      >
                        {card.priority}
                      </span>
                    </div>

                    <div className="flex items-center space-x-2 text-[10px] font-mono text-cyan-300 mb-1.5">
                      <span className="px-1 py-0.5 rounded bg-[#0d1c31] border border-[#1b3964]">
                        Type: {card.advisoryType}
                      </span>
                      <span>Downtime: {card.estimatedDowntime}</span>
                    </div>

                    <p className="text-[11px] font-mono text-slate-300 mb-2 leading-tight">
                      {card.description}
                    </p>

                    <div className="text-[10px] font-mono text-slate-400 border-t border-[#142338] pt-1.5 mb-2">
                      <div>Tools: {card.requiredTools}</div>
                      <div>Parts: {card.requiredParts}</div>
                    </div>

                    <div className="flex items-center space-x-2 pt-1 border-t border-[#142338]">
                      <button
                        onClick={() => moveCard(card.id, 'SCHEDULED')}
                        className="flex-1 py-1 rounded bg-[#102038] hover:bg-[#183054] text-slate-200 text-[10px] font-chakra font-bold border border-[#1e3c66] transition-colors"
                      >
                        Move to Scheduled &rarr;
                      </button>
                      <button
                        onClick={() => moveCard(card.id, 'COMPLETED')}
                        className="px-2 py-1 rounded bg-emerald-950/70 hover:bg-emerald-900 text-emerald-300 text-[10px] font-chakra font-bold border border-emerald-600 transition-colors"
                      >
                        ✓ Done
                      </button>
                    </div>
                  </div>
                ))}
            </div>
          </div>

          {/* COLUMN 2: SCHEDULED MAINTENANCE */}
          <div className="bg-[#070b13] p-2.5 rounded-lg border border-[#142338] flex flex-col min-h-[300px]">
            <div className="flex items-center justify-between pb-2 mb-2 border-b border-[#142338]">
              <span className="font-chakra font-bold text-xs text-cyan-400 uppercase flex items-center space-x-1.5">
                <span className="w-2 h-2 rounded-full bg-cyan-400" />
                <span>Scheduled Maintenance</span>
              </span>
              <span className="px-1.5 py-0.5 rounded text-[10px] font-mono bg-cyan-950/60 text-cyan-300 border border-cyan-800">
                {cards.filter((c) => c.status === 'SCHEDULED').length}
              </span>
            </div>

            <div className="space-y-2 flex-1 overflow-y-auto">
              {cards
                .filter((c) => c.status === 'SCHEDULED')
                .map((card) => (
                  <div key={card.id} className="p-2.5 rounded border bg-[#0a121e] border-[#182942]">
                    <div className="flex items-center justify-between text-[11px] font-chakra mb-1">
                      <span className="font-bold text-slate-100">{card.component}</span>
                      <span className="text-[9px] font-mono px-1 rounded bg-cyan-950 text-cyan-300 border border-cyan-800">
                        {card.priority}
                      </span>
                    </div>

                    <div className="flex items-center space-x-2 text-[10px] font-mono text-cyan-300 mb-1.5">
                      <span className="px-1 py-0.5 rounded bg-[#0d1c31] border border-[#1b3964]">
                        Type: {card.advisoryType}
                      </span>
                      <span>Downtime: {card.estimatedDowntime}</span>
                    </div>

                    <p className="text-[11px] font-mono text-slate-300 mb-2 leading-tight">
                      {card.description}
                    </p>

                    <div className="flex items-center space-x-2 pt-1 border-t border-[#142338]">
                      <button
                        onClick={() => moveCard(card.id, 'COMPLETED')}
                        className="w-full py-1 rounded bg-emerald-950/80 hover:bg-emerald-900 text-emerald-300 text-[10px] font-chakra font-bold border border-emerald-600 transition-colors flex items-center justify-center space-x-1"
                      >
                        <CheckCircle2 className="w-3 h-3" />
                        <span>MARK COMPLETE</span>
                      </button>
                    </div>
                  </div>
                ))}
            </div>
          </div>

          {/* COLUMN 3: COMPLETED TASKS */}
          <div className="bg-[#070b13] p-2.5 rounded-lg border border-[#142338] flex flex-col min-h-[300px]">
            <div className="flex items-center justify-between pb-2 mb-2 border-b border-[#142338]">
              <span className="font-chakra font-bold text-xs text-emerald-400 uppercase flex items-center space-x-1.5">
                <span className="w-2 h-2 rounded-full bg-emerald-400" />
                <span>Completed Tasks</span>
              </span>
              <span className="px-1.5 py-0.5 rounded text-[10px] font-mono bg-emerald-950/60 text-emerald-300 border border-emerald-800">
                {cards.filter((c) => c.status === 'COMPLETED').length}
              </span>
            </div>

            <div className="space-y-2 flex-1 overflow-y-auto">
              {cards
                .filter((c) => c.status === 'COMPLETED')
                .map((card) => (
                  <div key={card.id} className="p-2.5 rounded border bg-[#060c15] border-[#142338] opacity-75">
                    <div className="flex items-center justify-between text-[11px] font-chakra mb-1">
                      <span className="font-bold text-slate-300 line-through">{card.component}</span>
                      <span className="text-[9px] font-mono px-1 rounded bg-emerald-950 text-emerald-300 border border-emerald-800">
                        RESOLVED
                      </span>
                    </div>

                    <p className="text-[10px] font-mono text-slate-400 mb-2">
                      {card.description}
                    </p>

                    <button
                      onClick={() => moveCard(card.id, 'SCHEDULED')}
                      className="text-[9px] text-slate-400 hover:text-cyan-300 underline"
                    >
                      Reopen Task
                    </button>
                  </div>
                ))}
            </div>
          </div>
        </div>
      </section>

      {/* ========================================================================= */}
      {/* 2-COLUMN SPLIT: PANEL 2 (TIMELINE) & PANEL 3 (RUL & TBO TRACKER)          */}
      {/* ========================================================================= */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-3.5 items-start">
        {/* PANEL 2 — COMPONENT HEALTH TIMELINE (LAST 50 FLIGHT HOURS) (7 COLS) */}
        <div className="lg:col-span-7 bg-[#0a0e17] border border-[#16273f] rounded-lg p-3.5 shadow-md flex flex-col justify-between">
          <div className="flex items-center justify-between pb-2 mb-2 border-b border-[#142338]">
            <div className="flex items-center space-x-2">
              <Calendar className="w-4 h-4 text-cyan-400" />
              <h3 className="text-xs font-chakra font-bold tracking-wider text-slate-200 uppercase">
                PANEL 2: COMPONENT HEALTH TIMELINE [LAST 50 FLIGHT HOURS]
              </h3>
            </div>
            <span className="text-[10px] font-mono text-slate-400">Click component row for failure curve</span>
          </div>

          <div className="space-y-2 pt-1">
            {componentsTimelineData.map((comp) => {
              const h = comp.currentHealth;
              const isCrit = h < 70;
              const isWarn = h < 85 && !isCrit;

              return (
                <div
                  key={comp.id}
                  onClick={() => setSelectedComponentDetail(comp)}
                  className="p-2 rounded bg-[#070b13] border border-[#142338] hover:border-cyan-500/60 cursor-pointer transition-all flex flex-col space-y-1.5 group"
                >
                  <div className="flex items-center justify-between text-xs font-chakra">
                    <span className="font-bold text-slate-200 group-hover:text-cyan-300 transition-colors">
                      {comp.name}
                    </span>
                    <div className="flex items-center space-x-2 font-mono text-[10px]">
                      <span className="text-slate-400">Health:</span>
                      <span
                        className={`font-bold ${
                          isCrit ? 'text-rose-400' : isWarn ? 'text-amber-400' : 'text-emerald-400'
                        }`}
                      >
                        {h}%
                      </span>
                      <span className="text-slate-500">|</span>
                      <span className="text-slate-400">RUL: {comp.nextPredictedServiceHours}h</span>
                    </div>
                  </div>

                  {/* Horizontal Bar with color gradient from healthy to degraded */}
                  <div className="w-full h-2.5 bg-[#040810] rounded-sm overflow-hidden flex border border-[#142338]">
                    <div
                      className="h-full transition-all duration-500 ease-out"
                      style={{
                        width: `${Math.min(100, h)}%`,
                        background:
                          h >= 85
                            ? 'linear-gradient(90deg, #059669, #10b981)'
                            : h >= 70
                            ? 'linear-gradient(90deg, #d97706, #f59e0b)'
                            : 'linear-gradient(90deg, #dc2626, #ef4444)',
                      }}
                    />
                  </div>

                  <div className="flex items-center justify-between text-[9px] font-mono text-slate-400">
                    <span>T-50h (98%)</span>
                    <span>T-30h</span>
                    <span>T-10h</span>
                    <span className="text-cyan-400 font-bold">Sortie 027 (NOW: {h}%)</span>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* PANEL 3 — RUL & TBO TRACKER (5 COLS) */}
        <div className="lg:col-span-5 bg-[#0a0e17] border border-[#16273f] rounded-lg p-3.5 shadow-md flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between pb-2 mb-2 border-b border-[#142338]">
              <div className="flex items-center space-x-2">
                <Clock className="w-4 h-4 text-cyan-400" />
                <h3 className="text-xs font-chakra font-bold tracking-wider text-slate-200 uppercase">
                  PANEL 3: RUL & TBO OVERHAUL TRACKER
                </h3>
              </div>
              <span className="text-[10px] font-tech text-amber-400">ROTAX OEM LIMIT</span>
            </div>

            {/* TBO Countdown Card */}
            <div className="p-3 rounded bg-[#070b13] border border-[#142338] mb-3">
              <div className="flex items-center justify-between text-xs font-chakra mb-1">
                <span className="font-bold text-slate-300">TBO (TIME BETWEEN OVERHAULS)</span>
                <span className="font-mono text-cyan-400 font-bold">{tboTotalHours} HRS FACTORY SPEC</span>
              </div>
              <div className="flex items-baseline space-x-2 my-1">
                <span className="text-2xl font-tech font-extrabold text-amber-400">{tboRemainingHours}</span>
                <span className="text-xs font-chakra text-slate-400">HOURS REMAINING</span>
              </div>
              {/* Progress bar */}
              <div className="w-full h-2 bg-[#040810] rounded-sm overflow-hidden border border-[#142338]">
                <div
                  className="h-full bg-cyan-400 transition-all"
                  style={{ width: `${tboPercent}%` }}
                />
              </div>
              <div className="flex justify-between text-[9px] font-mono text-slate-400 mt-1">
                <span>Elapsed: {tboElapsedHours} hrs</span>
                <span>Threshold: Major Depot Overhaul</span>
              </div>
            </div>

            {/* Per-Component RUL Bars */}
            <div className="space-y-1.5 mb-3">
              <div className="text-[10px] font-chakra text-slate-400 uppercase font-bold">
                Subsystem Remaining Useful Life Bars:
              </div>
              {componentRulList.map((item, idx) => (
                <div key={idx} className="flex items-center justify-between text-xs font-chakra">
                  <span className="text-slate-300 w-32 truncate">{item.name}</span>
                  <div className="flex-1 mx-2 h-1.5 bg-[#070b13] rounded-sm overflow-hidden border border-[#142338]">
                    <div
                      className={`h-full ${
                        item.status === 'critical'
                          ? 'bg-rose-500'
                          : item.status === 'warning'
                          ? 'bg-amber-500'
                          : 'bg-cyan-400'
                      }`}
                      style={{ width: `${Math.min(100, (item.rul / item.max) * 100)}%` }}
                    />
                  </div>
                  <span
                    className={`font-mono text-[10px] w-14 text-right font-bold ${
                      item.status === 'critical' ? 'text-rose-400' : 'text-slate-300'
                    }`}
                  >
                    {item.rul} hrs
                  </span>
                </div>
              ))}
            </div>

            {/* Maintenance Window Optimizer */}
            <div className="p-2.5 rounded bg-cyan-950/30 border border-cyan-800/50">
              <div className="flex items-center space-x-1.5 text-xs font-chakra font-bold text-cyan-300 mb-1">
                <Sparkles className="w-3.5 h-3.5 text-cyan-400" />
                <span>MAINTENANCE WINDOW OPTIMIZER (AI)</span>
              </div>
              <p className="text-[11px] font-mono text-slate-300 leading-tight">
                Recommended Slot: <strong>Post-Mission 027 (Gap: 4.5 hrs before Sortie 028)</strong>. Performing injector service in this window avoids 18 hrs unscheduled AOG grounding.
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* ========================================================================= */}
      {/* PANEL 4 — PARTS INVENTORY & PROCUREMENT (AUTO-SUGGEST REORDERS)          */}
      {/* ========================================================================= */}
      <section className="bg-[#0a0e17] border border-[#16273f] rounded-lg p-3.5 shadow-md">
        <div className="flex items-center justify-between pb-2 mb-2 border-b border-[#142338]">
          <div className="flex items-center space-x-2">
            <Package className="w-4 h-4 text-emerald-400" />
            <h3 className="text-xs font-chakra font-bold tracking-wider text-slate-200 uppercase">
              PANEL 4: PARTS INVENTORY & PROCUREMENT [AUTO-REORDER LOGIC]
            </h3>
          </div>
          <span className="text-[10px] font-mono text-slate-400">Auto-suggest orders when RUL &lt; Lead Time</span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs font-tech">
            <thead className="bg-[#070b13] text-slate-400 border-b border-[#142338] text-[10px] uppercase font-chakra tracking-wider">
              <tr>
                <th className="py-2 px-3">PART DESCRIPTION</th>
                <th className="py-2 px-3 text-center">CURRENT STOCK</th>
                <th className="py-2 px-3 text-center">LEAD TIME</th>
                <th className="py-2 px-3 text-center">RECOMMENDED ORDER QTY</th>
                <th className="py-2 px-3 text-right">RUL REMAINING</th>
                <th className="py-2 px-3">PROCUREMENT STATUS</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#142338]">
              {inventoryItems.map((item, idx) => (
                <tr
                  key={idx}
                  className={`transition-colors ${
                    item.urgent
                      ? 'bg-rose-950/20 hover:bg-rose-950/30'
                      : 'hover:bg-[#070b13]'
                  }`}
                >
                  <td className="py-2.5 px-3 font-bold text-slate-200 font-chakra">
                    {item.partName}
                  </td>
                  <td className="py-2.5 px-3 text-center font-mono">
                    <span
                      className={`px-1.5 py-0.5 rounded font-bold ${
                        item.stock === 0
                          ? 'bg-rose-950 text-rose-300 border border-rose-600'
                          : 'bg-[#0d1624] text-slate-200'
                      }`}
                    >
                      {item.stock} ea
                    </span>
                  </td>
                  <td className="py-2.5 px-3 text-center font-mono text-slate-300">
                    {item.leadTimeDays} days
                  </td>
                  <td className="py-2.5 px-3 text-center font-mono text-cyan-400 font-bold">
                    +{item.reorderQty} units
                  </td>
                  <td className="py-2.5 px-3 text-right font-mono text-slate-200">
                    {item.rulHours} hrs
                  </td>
                  <td className="py-2.5 px-3">
                    <span
                      className={`px-2 py-0.5 rounded text-[10px] font-bold font-chakra ${
                        item.urgent
                          ? 'bg-rose-900/80 text-rose-200 border border-rose-500 animate-pulse'
                          : 'bg-emerald-950 text-emerald-300 border border-emerald-800'
                      }`}
                    >
                      {item.status}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
      </>
      )}

      {/* ========================================================================= */}
      {/* COMPONENT DETAIL MODAL (WHEN A TIMELINE COMPONENT IS CLICKED)              */}
      {/* ========================================================================= */}
      {selectedComponentDetail && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-xs animate-fadeIn">
          <div className="bg-[#0a0e17] border border-[#1a3252] rounded-lg max-w-2xl w-full p-4 shadow-2xl space-y-4">
            <div className="flex items-center justify-between pb-2 border-b border-[#16273f]">
              <div>
                <h4 className="font-chakra font-bold text-sm text-cyan-300">
                  {selectedComponentDetail.name}
                </h4>
                <div className="text-[10px] font-mono text-slate-400">
                  Category: {selectedComponentDetail.category} • OEM PN: {selectedComponentDetail.recommendedPartNumber}
                </div>
              </div>
              <button
                onClick={() => setSelectedComponentDetail(null)}
                className="p-1 rounded text-slate-400 hover:text-white"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Weibull Failure Probability Curve Chart */}
            <div className="bg-[#070b13] p-3 rounded border border-[#142338]">
              <div className="text-[10px] font-chakra font-bold text-slate-300 mb-1 flex justify-between">
                <span>WEIBULL CUMULATIVE FAILURE PROBABILITY CURVE</span>
                <span className="font-mono text-rose-400">Current P(f): {selectedComponentDetail.failureProbability}%</span>
              </div>
              <div className="h-36 w-full">
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart data={failureCurveData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#16273f" />
                    <XAxis dataKey="flightHours" stroke="#64748b" tick={{ fontSize: 9, fill: '#94a3b8' }} />
                    <YAxis domain={[0, 100]} stroke="#64748b" tick={{ fontSize: 9, fill: '#94a3b8' }} unit="%" />
                    <Tooltip
                      contentStyle={{
                        backgroundColor: '#0a162a',
                        borderColor: '#1e385c',
                        borderRadius: 4,
                        fontSize: 10,
                        color: '#fff',
                      }}
                    />
                    <Area type="monotone" dataKey="probability" stroke="#ef4444" fill="#ef4444" fillOpacity={0.2} />
                  </AreaChart>
                </ResponsiveContainer>
              </div>
            </div>

            {/* Diagnostics Stats Grid */}
            <div className="grid grid-cols-3 gap-2.5 text-xs font-chakra">
              <div className="p-2 rounded bg-[#070b13] border border-[#142338]">
                <div className="text-[9px] text-slate-400">WEAR RATE</div>
                <div className="font-tech font-bold text-amber-400 text-sm">{selectedComponentDetail.wearRate}% / hr</div>
              </div>
              <div className="p-2 rounded bg-[#070b13] border border-[#142338]">
                <div className="text-[9px] text-slate-400">LAST SERVICED</div>
                <div className="font-tech font-bold text-slate-200 text-xs">{selectedComponentDetail.lastServiceDate}</div>
              </div>
              <div className="p-2 rounded bg-[#070b13] border border-[#142338]">
                <div className="text-[9px] text-slate-400">NEXT PREDICTED SERVICE</div>
                <div className="font-tech font-bold text-cyan-400 text-sm">In {selectedComponentDetail.nextPredictedServiceHours} hrs</div>
              </div>
            </div>

            <div className="flex justify-end pt-2 border-t border-[#16273f]">
              <button
                onClick={() => setSelectedComponentDetail(null)}
                className="px-4 py-1.5 rounded bg-[#102038] hover:bg-[#183054] text-slate-200 font-chakra font-bold text-xs"
              >
                Close Component Details
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ========================================================================= */}
      {/* PANEL 5: MAINTENANCE REPORT GENERATOR MODAL                               */}
      {/* ========================================================================= */}
      {isReportModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-xs animate-fadeIn">
          <div className="bg-[#0a0e17] border border-[#1a3252] rounded-lg max-w-3xl w-full max-h-[90vh] flex flex-col shadow-2xl overflow-hidden">
            {/* Modal Header */}
            <div className="flex items-center justify-between px-4 py-3 bg-[#070b13] border-b border-[#16273f]">
              <div className="flex items-center space-x-2">
                <FileText className="w-5 h-5 text-cyan-400" />
                <h4 className="font-chakra font-bold text-sm text-slate-100 uppercase tracking-wider">
                  MISSION HEALTH & PREDICTIVE MAINTENANCE REPORT // MISSION-027
                </h4>
              </div>
              <button
                onClick={() => setIsReportModalOpen(false)}
                className="p-1 rounded text-slate-400 hover:text-white"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Modal Content (Printable / Exportable) */}
            <div className="p-4 flex-1 overflow-y-auto space-y-4 font-mono text-xs text-slate-200 bg-[#060a12]">
              {/* Mission Header */}
              <div className="p-3 rounded border border-[#16273f] bg-[#070b13] grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs">
                <div>
                  <span className="text-[10px] text-slate-400">MISSION ID:</span>
                  <div className="font-bold text-cyan-300">MISSION-027</div>
                </div>
                <div>
                  <span className="text-[10px] text-slate-400">DATE:</span>
                  <div>2026-09-26</div>
                </div>
                <div>
                  <span className="text-[10px] text-slate-400">SORTIE DURATION:</span>
                  <div>01:42:15 UTC</div>
                </div>
                <div>
                  <span className="text-[10px] text-slate-400">AIRFRAME / ENGINE:</span>
                  <div>UAV-07 / ROTAX 914-F</div>
                </div>
              </div>

              {/* Section 1: Engine Health Summary */}
              <div className="space-y-1">
                <h5 className="font-chakra font-bold text-cyan-400 text-xs uppercase">
                  1. Overall Engine Health Summary
                </h5>
                <p className="text-[11px] leading-relaxed text-slate-300">
                  Global engine health evaluated at <strong>{Math.round(health.overall)}%</strong> condition score.
                  Mechanical health is at <strong>{health.mechanical}%</strong>, thermal subsystem at <strong>{health.thermal}%</strong>,
                  and lubrication circuit at <strong>{health.lubrication}%</strong>. TBO countdown stands at <strong>{tboRemainingHours} hours</strong> remaining.
                </p>
              </div>

              {/* Section 2: Faults Detected */}
              <div className="space-y-1">
                <h5 className="font-chakra font-bold text-amber-400 text-xs uppercase">
                  2. In-Flight Faults & Anomalies Logged
                </h5>
                <div className="p-2 rounded bg-[#070b13] border border-[#16273f]">
                  <div>• Active Fault Mode: <strong className="text-amber-300">{activeFault}</strong></div>
                  <div>• Peak Anomaly Score: <strong>{(diagnostic.anomalyScore * 100).toFixed(0)}%</strong></div>
                  <div>• Signature Match: <strong>{diagnostic.probableFault}</strong> (Confidence: {diagnostic.confidence}%)</div>
                </div>
              </div>

              {/* Section 3: Actions Taken & Work Orders */}
              <div className="space-y-1">
                <h5 className="font-chakra font-bold text-cyan-400 text-xs uppercase">
                  3. Line Actions Taken (Kanban Audit)
                </h5>
                <ul className="list-disc pl-4 space-y-0.5 text-[11px] text-slate-300">
                  <li>Spark plug 8-point gap check completed at 0.70mm nominal.</li>
                  <li>Oil filter differential pressure spike logged; replacement scheduled.</li>
                  <li>Cylinder 2 injector nozzle ultrasonic cleaning advisory generated.</li>
                </ul>
              </div>

              {/* Section 4: Recommendations for Next Mission */}
              <div className="space-y-1">
                <h5 className="font-chakra font-bold text-emerald-400 text-xs uppercase">
                  4. Recommendations for Next Mission (Sortie 028)
                </h5>
                <p className="text-[11px] text-slate-300">
                  Perform post-mission 4.5-hour turnaround maintenance on Cylinder 2 fuel injector.
                  Replenish oil filter cartridge ROTAX-914-825-B before cruise climb authorization.
                </p>
              </div>
            </div>

            {/* Modal Actions Footer: PDF, CSV, Print */}
            <div className="px-4 py-3 bg-[#070b13] border-t border-[#16273f] flex items-center justify-between text-xs font-chakra">
              <span className="text-slate-400 text-[11px]">
                Authorized Sign-off: Chief Propulsion Technician (Level 3)
              </span>
              <div className="flex items-center space-x-2">
                <button
                  onClick={handleExportCsv}
                  className="px-3 py-1.5 rounded bg-[#102038] hover:bg-[#183054] border border-[#1e3c66] text-cyan-300 font-bold flex items-center space-x-1"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>EXPORT CSV</span>
                </button>
                <button
                  onClick={handlePrint}
                  className="px-3 py-1.5 rounded bg-[#102038] hover:bg-[#183054] border border-[#1e3c66] text-slate-200 font-bold flex items-center space-x-1"
                >
                  <Printer className="w-3.5 h-3.5" />
                  <span>PRINT / PDF</span>
                </button>
                <button
                  onClick={() => setIsReportModalOpen(false)}
                  className="px-3 py-1.5 rounded bg-cyan-950 hover:bg-cyan-900 border border-cyan-500/60 text-cyan-300 font-bold"
                >
                  CLOSE
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
